name: "GitHub Tag"
description: "Bump and push git tag on merge"
author: "Chris Hilton"
outputs:
  new_tag:
    description: "Generated tag"
  new_version:
    description: "Generated tag without the prefix"
  previous_version:
    description: "Previous version (or `0.0.0`)"
inputs:
  github_token:
    description: "Required for permission to tag the repo."
    required: true
  deployable_target:
    description: "The deployable target to bump the version of"
    required: true

runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "git-merge"
  color: "purple"
